/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JdRouteImport } from './routes/jd'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ResumeBuilderRouteImport } from './routes/resume-builder'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SkillMatchRouteImport } from './routes/skill-match'
import { Route as TalentCheckRouteImport } from './routes/talent-check'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JdRoute = JdRouteImport.update({
  id: '/jd',
  path: '/jd',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeBuilderRoute = ResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillMatchRoute = SkillMatchRouteImport.update({
  id: '/skill-match',
  path: '/skill-match',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentCheckRoute = TalentCheckRouteImport.update({
  id: '/talent-check',
  path: '/talent-check',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jd': typeof JdRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/resume': typeof ResumeRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skill-match': typeof SkillMatchRoute
  '/talent-check': typeof TalentCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jd': typeof JdRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/resume': typeof ResumeRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skill-match': typeof SkillMatchRoute
  '/talent-check': typeof TalentCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jd': typeof JdRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/resume': typeof ResumeRoute
  '/resume-builder': typeof ResumeBuilderRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skill-match': typeof SkillMatchRoute
  '/talent-check': typeof TalentCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jd'
    | '/login'
    | '/profile'
    | '/report'
    | '/resume'
    | '/resume-builder'
    | '/sitemap.xml'
    | '/skill-match'
    | '/talent-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jd'
    | '/login'
    | '/profile'
    | '/report'
    | '/resume'
    | '/resume-builder'
    | '/sitemap.xml'
    | '/skill-match'
    | '/talent-check'
  id:
    | '__root__'
    | '/'
    | '/jd'
    | '/login'
    | '/profile'
    | '/report'
    | '/resume'
    | '/resume-builder'
    | '/sitemap.xml'
    | '/skill-match'
    | '/talent-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JdRoute: typeof JdRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReportRoute: typeof ReportRoute
  ResumeRoute: typeof ResumeRoute
  ResumeBuilderRoute: typeof ResumeBuilderRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillMatchRoute: typeof SkillMatchRoute
  TalentCheckRoute: typeof TalentCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jd': {
      id: '/jd'
      path: '/jd'
      fullPath: '/jd'
      preLoaderRoute: typeof JdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-builder': {
      id: '/resume-builder'
      path: '/resume-builder'
      fullPath: '/resume-builder'
      preLoaderRoute: typeof ResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-match': {
      id: '/skill-match'
      path: '/skill-match'
      fullPath: '/skill-match'
      preLoaderRoute: typeof SkillMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-check': {
      id: '/talent-check'
      path: '/talent-check'
      fullPath: '/talent-check'
      preLoaderRoute: typeof TalentCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JdRoute: JdRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReportRoute: ReportRoute,
  ResumeRoute: ResumeRoute,
  ResumeBuilderRoute: ResumeBuilderRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillMatchRoute: SkillMatchRoute,
  TalentCheckRoute: TalentCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
